
spring:
        datasource:
          driver-class-name: com.mysql.jdbc.Driver
          username: db01
          password: 123456
          url: jdbc:mysql://192.168.18.128/dataGod?useUnicode=true&characterEncoding=utf-8&useSSL=false
        jpa:
          show-sql: true
server:
        port: 8080
        servlet:
          context-path: /sell

wechat:
        mpAppId: wxbbceea99fb9a5fa1
        mpAppSecret: 0dfa9ef62a531ff6504c0d9c3a78fb49

