
spring:
        datasource:
          druid:
            #数据库访问配置，使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            username: peacoke
            password: 123456
            url: jdbc:mysql://74.120.172.19/peacoke_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
            #连接池设置
            initial-size: 5
            min-idle: 5
            max-active: 20
            # 配置检测可以关闭的空闲连接间隔时间
            time-between-eviction-runs-millis: 60000
            # 配置连接在池中的最小生存时间
            min-evictable-idle-time-millis: 300000
            validation-query: select '1' from dual
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            max-pool-prepared-statement-per-connection-size: 20
            # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
            filters: stat,wall
            # WebStatFilter配置
            web-stat-filter:
              enabled: true
              # 添加过滤规则
              url-pattern: /*
              # 忽略过滤的格式
              exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

            # StatViewServlet配置
            stat-view-servlet:
              enabled: true
              # 访问路径为/druid时，跳转到StatViewServlet
              url-pattern: /druid/*
              # 是否能够重置数据
              reset-enable: false
              # 需要账号密码才能访问控制台
              login-username: druid
              login-password: druid123
              # IP白名单
              # allow: 127.0.0.1
              #　IP黑名单（共同存在时，deny优先于allow）
              # deny: 192.168.1.218

            # 配置StatFilter
            filter:
              stat:
                log-slow-sql: true
        #开启模板缓存（默认值：true）
        thymeleaf:
          cache: false
          check-template: true
          check-template-location: true
          servlet:
            content-type: text/html
          #开启MVC Thymeleaf视图解析（默认值：true）
          enabled: true
          encoding: UTF-8
          mode: HTML5
          prefix: classpath:/templates/
          suffix: .html
        #redis
        redis:
          host: 192.168.125.132
          database: 0
          port: 6379
server:
        port: 8080
        servlet:
          context-path: /sell
#Actuator配置
wechat:
        mpAppId: wxbbceea99fb9a5fa1
        mpAppSecret: 0dfa9ef62a531ff6504c0d9c3a78fb49
mybatis:
  mapper-locations: classpath:mapping/*Mapper*.xml
  type-aliases-package: com.work.bean
logging:
  level:
    com:
      work:
        dao: DEBUG






