
spring:
        datasource:
          driver-class-name: com.mysql.jdbc.Driver
          username: peacoke
          password: 123456
          url: jdbc:mysql://74.120.172.19/peacoke_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
        jpa:
          show-sql: true
          properties:
            hibernate:
              hbm2ddl:
                auto: update
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
        port: 8080
        servlet:
          context-path: /sell

wechat:
        mpAppId: wxbbceea99fb9a5fa1
        mpAppSecret: 0dfa9ef62a531ff6504c0d9c3a78fb49
mybatis:
  mapper-locations: classpath:mapping/*Mapper*.xml
  type-aliases-package: com.work.bean
logging:
  level:
    com:
      work:
        dao: DEBUG




